import = ["/Users/mykhailo/.config/alacritty/themes/tokyonight_storm.toml"]

[font]
size = 25

[font.normal]
family = "UbuntuMono Nerd Font"

[window]
decorations = "none"
opacity = 0.8
blur = false
startup_mode = "maximized"
dynamic_title = true
padding = {x = 0, y = 5}


[mouse]
hide_when_typing = true
